logging:
  level:
    ROOT: INFO

spring:
  application:
    name: cybereduc
    
  datasource:
    url: jdbc:postgresql://localhost:5432/cybereduc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL 
    show-sql: true 
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator.mappings: true
    hibernate:
      ddl-auto: update

# Tomcat conf
server:
  port: 8080

application:
  security:
    authentication:
      jwt:
        base64-secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
        expiration-time: 900000

# springdoc:
#   api-docs:
#     path: /api-docs
  # swagger-ui:
  #   path: /swagger-ui-custom.html
